import type {
  Position,
  MacroInfo,
  MonitorEvent,
  Prediction,
  StrategyRule,
  ExceptionCase,
  CapitalAllocation,
  KpiData,
} from './types';

// ============ 当前时间基准：交易日 14:35（已过14:30监测点，未到14:50收盘前总结）============
const NOW_ISO = '2026-06-26T14:35:00+08:00';

// ============ 1. 持仓数据（来自策略文档真实数据）============
export const positions: Position[] = [
  {
    id: 'csi300',
    name: '沪深300ETF',
    code: '510300',
    category: 'core',
    shares: 200,
    currentPrice: 5.048,
    costPrice: 4.984,
    targetShares: 1000,
    targetAddLines: { level1: -1.5, level2: -3.0 },
    takeProfitLine: 8,
    todayChange: 0.42,
    todayVolume: 1250,
    volumeChange: 8,
    ma5: 5.021,
    ma10: 4.988,
    macd: 0.012,
    kdj: 62.3,
  },
  {
    id: 'ai',
    name: '人工智能ETF',
    code: '515980',
    category: 'satellite',
    shares: 900,
    currentPrice: 2.180,
    costPrice: 2.112,
    targetAddLines: { level1: -2.0, level2: -4.0 },
    takeProfitLine: 10,
    todayChange: 2.85,
    todayVolume: 3420,
    volumeChange: 35,
    ma5: 2.135,
    ma10: 2.098,
    macd: 0.024,
    kdj: 78.6,
  },
  {
    id: 'chip',
    name: '芯片ETF',
    code: '512760',
    category: 'satellite',
    shares: 300,
    currentPrice: 3.175,
    costPrice: 2.881,
    targetAddLines: { level1: -3.0, level2: -5.0 },
    takeProfitLine: 15,
    todayChange: 1.92,
    todayVolume: 2180,
    volumeChange: 22,
    ma5: 3.142,
    ma10: 3.088,
    macd: 0.018,
    kdj: 71.2,
  },
  {
    id: 'battery',
    name: '电池ETF',
    code: '561910',
    category: 'satellite',
    shares: 500,
    currentPrice: 1.127,
    costPrice: 1.117,
    targetAddLines: { level1: -2.0, level2: -4.0 },
    takeProfitLine: 8,
    todayChange: -0.88,
    todayVolume: 860,
    volumeChange: -12,
    ma5: 1.142,
    ma10: 1.156,
    macd: -0.005,
    kdj: 38.5,
  },
  {
    id: 'robot',
    name: '机器人ETF',
    code: '562500',
    category: 'satellite',
    shares: 300,
    currentPrice: 1.400,
    costPrice: 1.470,
    targetAddLines: { level1: -2.5, level2: -5.0 },
    takeProfitLine: 10,
    todayChange: -1.45,
    todayVolume: 1420,
    volumeChange: 5,
    ma5: 1.421,
    ma10: 1.453,
    macd: -0.008,
    kdj: 32.1,
  },
];

// ============ 2. KPI 数据 ============
// 总持仓市值 + 现金
const positionValue = positions.reduce((sum, p) => sum + p.shares * p.currentPrice, 0);
const totalCost = positions.reduce((sum, p) => sum + p.shares * p.costPrice, 0);
const totalPnl = positionValue - totalCost;
const cashReserve = 500;
const totalAssets = positionValue + cashReserve;

export const kpiData: KpiData = {
  totalAssets: Number(totalAssets.toFixed(2)),
  totalPnl: Number(totalPnl.toFixed(2)),
  totalPnlPercent: Number(((totalPnl / totalCost) * 100).toFixed(3)),
  positionRatio: Number(((positionValue / totalAssets) * 100).toFixed(1)),
  cashReserve,
  todayAlerts: 3,
  todayPnl: 38.42,
  todayPnlPercent: 1.18,
};

// ============ 3. 资金分配 ============
export const capitalAllocation: CapitalAllocation[] = [
  {
    category: '核心底仓',
    amount: Number((positions[0].shares * positions[0].currentPrice).toFixed(2)),
    percentage: Number(((positions[0].shares * positions[0].currentPrice / totalAssets) * 100).toFixed(1)),
    color: 'var(--chart-1)',
    description: '沪深300ETF 目标1000股 / 占比≥40%',
  },
  {
    category: '卫星仓位',
    amount: Number(positions.slice(1).reduce((s, p) => s + p.shares * p.currentPrice, 0).toFixed(2)),
    percentage: Number((positions.slice(1).reduce((s, p) => s + p.shares * p.currentPrice, 0) / totalAssets * 100).toFixed(1)),
    color: 'var(--chart-4)',
    description: 'AI / 芯片 / 电池 / 机器人 攒筹码为主',
  },
  {
    category: '备用金',
    amount: cashReserve,
    percentage: Number(((cashReserve / totalAssets) * 100).toFixed(1)),
    color: 'var(--chart-3)',
    description: '账户预留500元，确保加仓/定投有资金',
  },
];

// ============ 4. 宏观信息流 ============
export const macroInfos: MacroInfo[] = [
  {
    id: 'm1',
    source: 'official',
    sourceName: '央行官网',
    sourceWeight: 90,
    title: '央行下调存款准备金率0.25个百分点',
    content: '中国人民银行决定于2026年7月15日起下调金融机构存款准备金率0.25个百分点，预计释放长期资金约5000亿元。此次降准旨在保持流动性合理充裕，促进综合融资成本稳中有降。',
    sentiment: 'positive',
    sentimentScore: 0.72,
    publishedAt: '2026-06-26T10:15:00+08:00',
    relatedEtfs: ['csi300', 'ai', 'chip'],
    impact: 'high',
  },
  {
    id: 'm2',
    source: 'official',
    sourceName: '国家发改委',
    sourceWeight: 90,
    title: '国家投入1000亿支持人工智能产业发展',
    content: '发改委联合多部门发布《人工智能产业高质量发展行动计划》，明确未来三年投入1000亿元支持AI芯片、大模型、智能应用等关键环节，提出2027年AI核心产业规模超1万亿目标。',
    sentiment: 'positive',
    sentimentScore: 0.85,
    publishedAt: '2026-06-26T09:30:00+08:00',
    relatedEtfs: ['ai', 'chip'],
    impact: 'high',
  },
  {
    id: 'm3',
    source: 'media',
    sourceName: '财新',
    sourceWeight: 70,
    title: '5月PMI数据公布：49.8，低于荣枯线',
    content: '国家统计局公布5月制造业PMI为49.8%，较上月下降0.2个百分点，连续两个月处于荣枯线下方。新订单指数49.5%，新出口订单指数48.2%，反映需求端持续偏弱。',
    sentiment: 'negative',
    sentimentScore: -0.55,
    publishedAt: '2026-06-26T09:00:00+08:00',
    relatedEtfs: ['csi300'],
    impact: 'high',
  },
  {
    id: 'm4',
    source: 'geopolitical',
    sourceName: 'CSIS 地缘冲突数据库',
    sourceWeight: 50,
    title: '某国拟扩大对华芯片出口管制范围',
    content: '据CSIS监测，某国商务部拟将14nm以下制程设备及HBM内存纳入对华出口管制清单，预计下周正式公告。涉及企业包括多家国内晶圆代工及存储芯片厂商。',
    sentiment: 'negative',
    sentimentScore: -0.68,
    publishedAt: '2026-06-26T11:20:00+08:00',
    relatedEtfs: ['chip'],
    impact: 'high',
  },
  {
    id: 'm5',
    source: 'industry',
    sourceName: '中信证券研报',
    sourceWeight: 50,
    title: '宁德时代发布麒麟电池5.0，能量密度提升20%',
    content: '中信证券新能源团队点评：宁德时代新一代麒麟电池5.0能量密度达320Wh/kg，预计2026Q4量产。建议关注动力电池产业链上游材料、设备环节投资机会。',
    sentiment: 'positive',
    sentimentScore: 0.42,
    publishedAt: '2026-06-26T13:45:00+08:00',
    relatedEtfs: ['battery'],
    impact: 'medium',
  },
  {
    id: 'm6',
    source: 'sentiment',
    sourceName: '雪球/微博热搜',
    sourceWeight: 30,
    title: '"AI ETF必涨到100元"话题登上热搜',
    content: '雪球热门讨论话题中，"AI ETF必涨到100元"登上热搜第8位，转发量超2万。情绪分析显示极端乐观情绪占比62%，已触发情绪过热过滤规则（权重<60%过滤）。',
    sentiment: 'positive',
    sentimentScore: 0.92,
    publishedAt: '2026-06-26T12:30:00+08:00',
    relatedEtfs: ['ai'],
    impact: 'low',
  },
  {
    id: 'm7',
    source: 'media',
    sourceName: '华尔街见闻',
    sourceWeight: 70,
    title: '人形机器人产业大会明日召开',
    content: '2026国际人形机器人产业大会将于明日（6月27日）在上海召开，特斯拉Optimus、宇树科技、智元机器人等将展示最新原型机。市场预期产业链订单有望加速落地。',
    sentiment: 'positive',
    sentimentScore: 0.48,
    publishedAt: '2026-06-26T14:00:00+08:00',
    relatedEtfs: ['robot'],
    impact: 'medium',
  },
];

// ============ 5. 监测事件（时间轴）============
export const monitorEvents: MonitorEvent[] = [
  {
    id: 'e1',
    triggerTime: '10:30',
    triggerType: 'intraday',
    triggerPoint: '10:30 开盘后监测',
    eventType: 'market',
    level: 'warn',
    title: '人工智能ETF 涨幅2.85%，成交量放大35%',
    content: '人工智能ETF（515980）10:30 报2.180元，涨幅2.85%，成交量3420万手，较昨日放大35%。已触发一级关注阈值（涨幅>2%且量能放大>30%）。',
    relatedEtfs: ['ai'],
    suggestions: ['关注止盈线（10%），当前持仓盈亏+3.22%未触发', '若午后涨幅扩大至5%，触发止盈条件，建议卖出整百股'],
    status: 'completed',
  },
  {
    id: 'e2',
    triggerTime: '10:30',
    triggerType: 'intraday',
    triggerPoint: '10:30 开盘后监测',
    eventType: 'macro',
    level: 'info',
    title: '央行降准0.25个百分点 - 宏观突发',
    content: '央行官网10:15发布公告，下调存款准备金率0.25个百分点，释放长期资金约5000亿元。来源权重90%（官方权威），情绪正面（+0.72）。',
    relatedEtfs: ['csi300', 'ai', 'chip'],
    suggestions: ['预计沪深300ETF明日高开0.5%-0.8%', '可关注1.5%加仓线，分批补仓至目标1000股'],
    status: 'completed',
  },
  {
    id: 'e3',
    triggerTime: '11:20',
    triggerType: 'intraday',
    triggerPoint: '盘中实时监测',
    eventType: 'macro',
    level: 'critical',
    title: '地缘突发：某国拟扩大芯片出口管制',
    content: 'CSIS监测显示某国拟将14nm以下制程设备及HBM内存纳入对华出口管制。来源权重50%（地缘监测），情绪负面（-0.68），影响等级：高。',
    relatedEtfs: ['chip'],
    suggestions: ['触发"地缘紧张"策略规则：暂停芯片ETF加仓', '若芯片ETF涨幅达5%，提前止盈卖出20%（60股）', '关注避险资产，避免恐慌中买入'],
    status: 'completed',
  },
  {
    id: 'e4',
    triggerTime: '14:00',
    triggerType: 'intraday',
    triggerPoint: '14:00 午盘后监测',
    eventType: 'market',
    level: 'info',
    title: '14:00 各ETF运行平稳，无异常波动',
    content: '14:00 监测点：5只ETF均在当日波动阈值内运行。人工智能ETF涨幅2.85%（阈值5%）、芯片ETF涨幅1.92%、沪深300ETF涨幅0.42%、电池ETF跌幅0.88%、机器人ETF跌幅1.45%。',
    status: 'completed',
  },
  {
    id: 'e5',
    triggerTime: '14:30',
    triggerType: 'intraday',
    triggerPoint: '14:30 收盘前监测',
    eventType: 'market',
    level: 'warn',
    title: '机器人ETF 跌幅1.45%，临近5日均线下方',
    content: '机器人ETF（562500）14:30 报1.400元，跌幅1.45%，已跌破5日均线（1.421）和10日均线（1.453）。KDJ指标32.1，短期承压。',
    relatedEtfs: ['robot'],
    suggestions: ['当前持仓盈亏-4.762%，距-5%二级加仓线仅0.24%', '若尾盘跌幅扩大至2.5%，触发一级加仓条件', '关注明日人形机器人产业大会催化'],
    status: 'completed',
  },
  {
    id: 'e6',
    triggerTime: '14:50',
    triggerType: 'pre-close',
    triggerPoint: '14:50 收盘前总结（待触发）',
    eventType: 'summary',
    level: 'info',
    title: '14:50 收盘前总结 + 次日预测（待生成）',
    content: '系统将在14:50自动生成当日总结（5只ETF涨跌幅/持仓盈亏/宏观事件影响）+ 次日预测（ARIMA模型开盘价区间/涨跌幅区间）+ 操作建议。',
    status: 'pending',
  },
  {
    id: 'e7',
    triggerTime: '16:30',
    triggerType: 'post-close',
    triggerPoint: '16:30 盘后复盘（待触发）',
    eventType: 'review',
    level: 'info',
    title: '16:30 盘后复盘 + 未来3日预测（待生成）',
    content: '系统将在16:30自动生成盘后深度分析：技术指标（5日/10日均线、MACD、KDJ）+ 宏观复盘 + LSTM未来3日涨跌幅区间 + 长/短期策略建议。',
    status: 'pending',
  },
];

// ============ 6. 预测数据 ============
export const predictions: Prediction[] = [
  {
    etfId: 'csi300',
    etfName: '沪深300ETF',
    nextDayOpenLow: 5.06,
    nextDayOpenHigh: 5.12,
    nextDayChangeLow: 0.2,
    nextDayChangeHigh: 1.4,
    threeDayChangeLow: 0.8,
    threeDayChangeHigh: 2.5,
    trend: 'up',
    confidence: 0.78,
    keyTriggers: ['央行降准利好', 'PMI<50或触发逆周期政策加码', '关注1.5%加仓线'],
  },
  {
    etfId: 'ai',
    etfName: '人工智能ETF',
    nextDayOpenLow: 2.20,
    nextDayOpenHigh: 2.25,
    nextDayChangeLow: 0.9,
    nextDayChangeHigh: 3.2,
    threeDayChangeLow: 2.0,
    threeDayChangeHigh: 4.5,
    trend: 'up',
    confidence: 0.72,
    keyTriggers: ['国家千亿AI投资政策利好', '情绪过热风险（热搜过滤）', '止盈线10%'],
  },
  {
    etfId: 'chip',
    etfName: '芯片ETF',
    nextDayOpenLow: 3.18,
    nextDayOpenHigh: 3.24,
    nextDayChangeLow: 0.2,
    nextDayChangeHigh: 2.2,
    threeDayChangeLow: -1.5,
    threeDayChangeHigh: 3.0,
    trend: 'flat',
    confidence: 0.58,
    keyTriggers: ['地缘管制利空 vs 国产替代逻辑', '已触发"地缘紧张"规则暂停加仓', '关注5%止盈卖出20%'],
  },
  {
    etfId: 'battery',
    etfName: '电池ETF',
    nextDayOpenLow: 1.11,
    nextDayOpenHigh: 1.14,
    nextDayChangeLow: -1.2,
    nextDayChangeHigh: 1.2,
    threeDayChangeLow: -2.0,
    threeDayChangeHigh: 1.5,
    trend: 'down',
    confidence: 0.61,
    keyTriggers: ['5日均线下方，短期承压', '宁德时代麒麟5.0催化或反弹', '关注-2%一级加仓线'],
  },
  {
    etfId: 'robot',
    etfName: '机器人ETF',
    nextDayOpenLow: 1.38,
    nextDayOpenHigh: 1.43,
    nextDayChangeLow: -1.4,
    nextDayChangeHigh: 2.1,
    threeDayChangeLow: -1.0,
    threeDayChangeHigh: 3.5,
    trend: 'flat',
    confidence: 0.65,
    keyTriggers: ['明日人形机器人产业大会催化', '已破5日/10日均线，技术面弱', '关注-2.5%一级加仓线'],
  },
];

// ============ 7. 策略调整规则 ============
export const strategyRules: StrategyRule[] = [
  {
    id: 'r1',
    macroType: '政策利好',
    trigger: '产业扶持政策（如"国家投入1000亿支持AI"）',
    adjustment: '提高AI ETF加仓线（-3%→-2%）、止盈线（8%→10%）',
    example: '若AI ETF跌2%，触发一级加仓',
    isActive: true,
    activeReason: '国家发改委今日发布千亿AI产业计划',
    icon: 'trending-up',
  },
  {
    id: 'r2',
    macroType: '地缘紧张',
    trigger: '重大地缘冲突（如"某国限制芯片出口"）',
    adjustment: '暂停所有ETF加仓、提前止盈（如芯片ETF涨5%卖出20%）',
    example: '避免恐慌中买入',
    isActive: true,
    activeReason: 'CSIS监测到芯片出口管制扩大',
    icon: 'alert-triangle',
  },
  {
    id: 'r3',
    macroType: '经济数据不及预期',
    trigger: 'PMI<50（经济下行）',
    adjustment: '降低定投金额（沪深300从500→300元/周）、增加备用金（10%→20%）',
    example: '减少资金投入',
    isActive: true,
    activeReason: '5月PMI 49.8，连续2月低于荣枯线',
    icon: 'trending-down',
  },
  {
    id: 'r4',
    macroType: '市场情绪过热',
    trigger: '社交媒体情绪指数>80（过热）',
    adjustment: '提高AI ETF止盈比例（20%→30%）、暂停加仓',
    example: '锁定利润，避免高位买入',
    isActive: false,
    activeReason: '当前情绪指数68，未达80阈值',
    icon: 'flame',
  },
];

// ============ 8. 异常处理 ============
export const exceptionCases: ExceptionCase[] = [
  {
    id: 'ex1',
    scenario: '盘中数据延迟',
    handling: '用缓存数据（前一分钟）替代，标注"数据延迟"',
    notifyMethod: '正常汇报',
    level: 'info',
  },
  {
    id: 'ex2',
    scenario: '预测模型误差',
    handling: '用历史平均涨幅替代，标注"预测仅供参考"',
    notifyMethod: '正常汇报',
    level: 'warn',
  },
  {
    id: 'ex3',
    scenario: '重大地缘事件（如战争）',
    handling: '触发紧急汇报：发送"暂停加仓，关注避险资产"',
    notifyMethod: '紧急推送（短信/APP）',
    level: 'critical',
  },
];

// ============ 9. 沪深300补仓进度 ============
export const csi300Progress = {
  current: positions[0].shares,
  target: 1000,
  remaining: 1000 - positions[0].shares,
  currentAmount: Number((positions[0].shares * positions[0].currentPrice).toFixed(2)),
  targetAmount: Number((1000 * positions[0].currentPrice).toFixed(2)),
  timeline: '3个月',
  weeklyInvest: 500, // 每周定投金额
  weeksNeeded: Math.ceil((1000 - positions[0].shares) * positions[0].currentPrice / 500),
};

// ============ 10. 实时时间基准 ============
export const currentTimestamp = NOW_ISO;

// 来源权重映射
export const sourceWeightMap: Record<string, number> = {
  official: 90,
  media: 70,
  industry: 50,
  geopolitical: 50,
  sentiment: 30,
};

export const sourceLabelMap: Record<string, string> = {
  official: '官方权威',
  media: '财经媒体',
  industry: '行业小众',
  geopolitical: '地缘监测',
  sentiment: '舆情情绪',
};
